"""insert roles

Revision ID: f1ac94f3ee8b
Revises: adffc978038d
Create Date: 2024-12-23 08:59:48.661024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.entity.models import Role, RoleEnum


# revision identifiers, used by Alembic.
revision: str = 'f1ac94f3ee8b'
down_revision: Union[str, None] = 'adffc978038d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(Role.__table__, [{'id': 1, 'name': RoleEnum.user.value}, 
                                    {'id': 2, 'name': RoleEnum.moderator.value}, 
                                    {'id': 3, 'name': RoleEnum.admin.value}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
