"""hotfix

Revision ID: 17a310771745
Revises: b572a894bd75
Create Date: 2024-12-21 11:04:27.795055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a310771745'
down_revision: Union[str, None] = 'b572a894bd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformations', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('transformations_photo_id_fkey', 'transformations', type_='foreignkey')
    op.create_foreign_key(None, 'transformations', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transformations', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformations', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transformations', type_='foreignkey')
    op.create_foreign_key('transformations_photo_id_fkey', 'transformations', 'posts', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transformations', 'post_id')
    # ### end Alembic commands ###
